/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gemini.voicerecognizer

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    println("Jose Luis Hurtado Balcazar")
    val pi=3.1416
    var dinero=10
    val nombre="Jose"
    val boolean=true
    val numeroLargo = 3L
    val double = 2.7182
    val p1=1
    val p2=2
    val p3=p1-p2
    println(p3)
    println("Uso de $: $dinero")
    if (nombre.isNotEmpty()){
        println("Nombre tiene una longitud de ${nombre.length}.")
    }else if(nombre.isEmpty()){
        println("OK!")    
    }else{
        println("Error.")
    }
    
    when (nombre){
        "Jose" -> println("Luis")
        "Luis" -> println("Migul")
    }

}
